### ISSUE TITLE
最新版与ComfyUI的最新版好像不兼容

### ISSUE THREAD

**Issue by BoosterCore** [ainewsto/Comfyui_Comfly#6]
```
Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\ComfyUI\main.py", line 231, in <module>
    server.add_routes()
  File "K:\ComfyUI_windows_portable\ComfyUI\server.py", line 573, in add_routes
    self.app.add_routes(api_routes)
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 373, in add_routes
    return self.router.add_routes(routes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1214, in add_routes
    registered_routes.extend(route_def.register(self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_routedef.py", line 76, in register
    return [reg(self.path, self.handler, **self.kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1175, in add_get
    resource.add_route(hdrs.METH_HEAD, handler, **kwargs)
  File "K:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 356, in add_route
    raise RuntimeError(
RuntimeError: Added route will never be executed, method HEAD is already registered
```

**Comment by ainewsto** [comment]
hello，刚刚看了下，是我眼花重复了一个路由，已经修改，并且也改为了特定的GET和POST，请更新插件，如果更新出现提示，比如文件夹得一些内容js或者py可以手动找到删除，再点更新就可以了

**Comment by BoosterCore** [comment]
> hello，刚刚看了下，是我眼花重复了一个路由，已经修改，并且也改为了特定的GET和POST，请更新插件，如果更新出现提示，比如文件夹得一些内容js或者py可以手动找到删除，再点更新就可以了

更新后，好像并没有任何变化，启动时还是卡在这一步就起不来了。对于您说的手动查找删除，我没太理解，因为不太了解编程。
会不会还跟其它插件有冲突呢？

**Comment by ainewsto** [comment]
> > hello，刚刚看了下，是我眼花重复了一个路由，已经修改，并且也改为了特定的GET和POST，请更新插件，如果更新出现提示，比如文件夹得一些内容js或者py可以手动找到删除，再点更新就可以了
> 
> 更新后，好像并没有任何变化，启动时还是卡在这一步就起不来了。对于您说的手动查找删除，我没太理解，因为不太了解编程。 会不会还跟其它插件有冲突呢？

就是点Update的时候，bat启动后端会显示更新的具体进度和信息，目前我测试没有遇到这样的问题，方便发完整的log给我吗？

**Comment by BoosterCore** [comment]
探讨下来，这个问题未必是Comfly和ComfyUI的问题，或许是其它插件的冲突。
